version: "2"

services:
    db:
        build: ./gws-core/src/test/docker/database
        image: gws/db
        ports:
            - "5433:5432"
    tomcat:
        build: ./gws-tomcat
        image: gws/tomcat
    web:
        build:
            context: ./gws-webapp/
            dockerfile: ./src/main/docker/webserver/Dockerfile
            args:
                - https_proxy
        image: gws/webserver
        depends_on:
            - db
            - tomcat
        ports:
            - "8081:8080"
    geoserver:
        build:
            context: ./gws-geoserver/
            dockerfile: ./Dockerfile
            args:
                - https_proxy
        image: gws/geoserver
        depends_on:
            - db
            - tomcat
        ports:
            - "8082:8080"
