version: 0.0
os: linux
files:
    - source: ./deploy-code/data
      destination: /usr/share/tomcat8/webapps/geoserver/data
    - source: ./deploy-code/geoserver.xml
      destination: /usr/share/tomcat8/conf/Catalina/localhost
hooks:
  BeforeInstall:
    - location: before-install.sh
  AfterInstall:
    - location: after-install.sh
  ValidateService:
    - location: validate-service.sh
